# Minimal GridWorld + SRPI config
experiment:
  name: gridworld_min
  seed: 42
  output_dir: experiments/gridworld_min

env:
  type: GridWorld
  size: 5            # 5x5 grid
  start: [0, 0]
  goal: [4, 4]
  step_penalty: -0.01
  goal_reward: 1.0
  max_steps: 40

agent:
  policy_hidden: 64
  gamma: 0.99
  entropy_coef: 0.01
  kl_coef: 0.0

lac:
  enabled: true
  alpha: 0.5          # blend weight between LAC and env advantages
  sigma_max: 1.0      # uncertainty gate
  hidden: 64
  lr: 1e-3

train:
  episodes: 300
  lr: 5e-3
  log_every: 10
  eval_every: 50
