agent:
  policy: greedy_manhattan_then_explore
env:
  goal:
  - 4
  - 4
  goal_reward: 1.0
  max_steps: 40
  size: 5
  start:
  - 0
  - 0
  step_penalty: -0.01
  type: GridWorld
experiment:
  name: reflection_timing
  output_dir: experiments/reflection_timing
  seed: 123
log:
  log_every: 1
reflect:
  episodes_per_mode: 60
  exploration_eps: 0.1
  memory_capacity: 32
  modes:
  - no_reflection
  - per_step
  - failure_only
  - success_only
