name: Build LaTeX PDF
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile paper with LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: paper_reflection_timing.tex
          args: -pdf -file-line-error -interaction=nonstopmode -f

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper_pdf
          path: paper_reflection_timing.pdf
